version: "3.9"
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=assignment
    ports:
      - "5432:5432"

  api:
    container_name: api
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/var/lib/postgresql/data
    depends_on:
      - postgres
    networks:
      - services-network

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - services-network

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - services-network

networks:
  services-network:
    driver: bridge