version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=assignment
    ports:
      - "5432:5432"
    networks:
      - services-network

  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - services-network

networks:
  services-network:
    driver: bridge